# Generated by Django 4.2.2 on 2024-02-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_App', '0002_question_qid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
